### ISSUE TITLE
splitOnChars not supported?

### ISSUE THREAD

**Issue by umakantozy** [clampy-js/react-clampy#2]
I do not see an example for splitOnChars property and looking at source code also doesn't seem it uses that as prop. Can we please add it ?

**Comment by alexandremoore** [comment]
@umakantozy It should be now available in version 1.3.0+
`splitOnChars={[".",",",""]}`

It determines what characters to use to chunk an element into smaller pieces. For example, it you pass an array of ['.', ',', ' '] then it will first remove sentences, then remove comma-phrases, and remove words, and finally remove individual characters to try and find the correct height. This will lead to increased performance and less looping when removing larger pieces of text (such as in paragraphs). The default is set to remove sentences (periods), hypens, en-dashes, em-dashes, and finally words (spaces). Removing by character is always enabled as the last attempt no matter what is submitted in the array.
